version: 2.1
orbs:
  aws-sam-serverless: circleci/aws-sam-serverless@dev:<<pipeline.git.revision>>
  orb-tools: circleci/orb-tools@11.1
filters: &filters
  tags:
    only: /.*/
jobs:
  # Define one or more jobs which will utilize your orb's commands and parameters to validate your changes.
  test_local_invoke:
    machine:
      image: ubuntu-2004:202101-01
    steps:
      - checkout
      - sam/install:
          version: v1.23.0 # Fixed until sam-cli issue is resolved https://github.com/aws/aws-sam-cli/issues/2927
      - sam/local-start-api:
          template: "./sample_test/sam-app/template.yaml"
          endpoint: "hello"
workflows:
  test-deploy:
    jobs:
      # Make sure to include "filters: *filters" in every test job you want to run as part of your deployment.
      - test_local_invoke:
          context: [CPE_ORBS_AWS]
          filters: *filters
      - sam/deploy:
          capabilities: CAPABILITY_IAM, CAPABILITY_NAMED_IAM
          name: deploy-job-test-app
          template: "./sample_test/sam-app/template.yaml"
          stack-name: "orb-deploy-job-test-1"
          s3-bucket: "sam-orb-testing"
          context: [CPE_ORBS_AWS]
          filters: *filters
      - sam/deploy:
          capabilities: CAPABILITY_IAM, CAPABILITY_NAMED_IAM
          name: deploy-job-test-container
          template: "./sample_test/sam-container/template.yaml"
          stack-name: "orb-deploy-job-test-2"
          image-repositories: $DEMO_IMG_URI
          context: [CPE_ORBS_AWS]
          validate: false
          filters: *filters
      - orb-tools/pack:
          filters: *filters
      - orb-tools/publish:
          orb-name: circleci/aws-sam-serverless
          vcs-type: << pipeline.project.type >>
          pub-type: production
          requires:
            - orb-tools/pack
            - test_local_invoke
            - deploy-job-test-app
            - deploy-job-test-container
          context: orb-publisher
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /^v[0-9]+\.[0-9]+\.[0-9]+$/
