version: 2.1
orbs:
  orb-tools: circleci/orb-tools@12.0
  aws-cli: circleci/aws-cli@5.1.1
  sam: {}
filters: &filters
  tags:
    only: /.*/
release-filters: &release-filters
  branches:
    ignore: /.*/
  tags:
    only: /^v[0-9]+\.[0-9]+\.[0-9]+$/
jobs:
  # Define one or more jobs which will utilize your orb's commands and parameters to validate your changes.
  temp-cleanup:
    docker:
    - image: cimg/base:stable
    steps:
      - aws-cli/setup:
          role_arn: arn:aws:iam::122211685980:role/CPE_SAM_SEVERLESS_OIDC_TEST
          profile_name: OIDC-User
      - run: |
          aws cloudformation delete-stack --stack-name orb-deploy-job-test-1 --profile OIDC-User
  cleanup:
    docker:
    - image: cimg/base:stable
    steps:
      - aws-cli/setup:
          role_arn: arn:aws:iam::122211685980:role/CPE_SAM_SEVERLESS_OIDC_TEST
          profile_name: OIDC-User
      - run: |
          aws cloudformation delete-stack --stack-name orb-deploy-job-test-1 --profile OIDC-User
          aws cloudformation delete-stack --stack-name orb-deploy-job-test-2 --profile OIDC-User
  test_local_invoke:
    machine:
      image: ubuntu-2004:2024.08.1
    steps:
      - checkout
      - aws-cli/setup:
          role_arn: arn:aws:iam::122211685980:role/CPE_SAM_SEVERLESS_OIDC_TEST
          profile_name: OIDC-User
      - sam/install:
          version: 1.57.0
      - sam/local_start_api:
          template: "./sample_test/sam-app/template.yaml"
          endpoint: "hello"
workflows:
  test-deploy:
    jobs:
      # Make sure to include "filters: *filters" in every test job you want to run as part of your deployment.
      - temp-cleanup:
          context: CPE-OIDC
      - test_local_invoke:
          context: CPE-OIDC
          filters: *filters
      - sam/deploy:
          name: deploy-job-test-app
          auth:
            - aws-cli/setup:
                role_arn: arn:aws:iam::122211685980:role/CPE_SAM_SEVERLESS_OIDC_TEST
                profile_name: OIDC-User
          profile_name: OIDC-User
          capabilities: CAPABILITY_IAM, CAPABILITY_NAMED_IAM
          template: "./sample_test/sam-app/template.yaml"
          stack_name: "orb-deploy-job-test-1"
          s3_bucket: "sam-orb-testing"
          context: CPE-OIDC
          filters: *filters
          requires:
          - temp-cleanup
      - sam/deploy:
          name: deploy-job-test-app-overrides-and-arguments
          auth:
            - aws-cli/setup:
                role_arn: arn:aws:iam::122211685980:role/CPE_SAM_SEVERLESS_OIDC_TEST
                profile_name: OIDC-User
          profile_name: OIDC-User
          capabilities: CAPABILITY_IAM, CAPABILITY_NAMED_IAM
          requires:
          - deploy-job-test-app
          template: "./sample_test/sam-app/template.yaml"
          stack_name: "orb-deploy-job-test-1"
          s3_bucket: "sam-orb-testing"
          parameter_overrides: ParameterKey=dummy,ParameterValue=dummy
          arguments:  --disable-rollback
          build_container_vars:  Function1.GITHUB_TOKEN=VAR1, GLOBAL_ENV_VAR=VAR2
          build_arguments: --parallel
          build_parameter_overrides: BuildParameterKey=dummy,BuildParameterValue=dummy
          context: CPE-OIDC
          filters: *filters
      - sam/deploy:
          name: deploy-job-test-app-multiline-arguments
          auth:
            - aws-cli/setup:
                role_arn: arn:aws:iam::122211685980:role/CPE_SAM_SEVERLESS_OIDC_TEST
                profile_name: OIDC-User
          profile_name: OIDC-User
          capabilities: CAPABILITY_IAM, CAPABILITY_NAMED_IAM
          template: "./sample_test/sam-app/template.yaml"
          stack_name: "orb-deploy-job-test-1"
          s3_bucket: "sam-orb-testing"
          requires:
          - deploy-job-test-app-overrides-and-arguments
          arguments: >-
            --disable-rollback
            --debug
          build_container_vars:  Function1.GITHUB_TOKEN=VAR1, GLOBAL_ENV_VAR=VAR2
          build_arguments: >-
            --parallel
            --debug
          context: CPE-OIDC
          filters: *filters
      - sam/deploy:
          name: deploy-job-test-app-same-line-arguments
          auth:
            - aws-cli/setup:
                role_arn: arn:aws:iam::122211685980:role/CPE_SAM_SEVERLESS_OIDC_TEST
                profile_name: OIDC-User
          profile_name: OIDC-User
          capabilities: CAPABILITY_IAM, CAPABILITY_NAMED_IAM
          template: "./sample_test/sam-app/template.yaml"
          stack_name: "orb-deploy-job-test-1"
          requires:
          - deploy-job-test-app-multiline-arguments
          s3_bucket: "sam-orb-testing"
          arguments: --disable-rollback --debug
          build_container_vars:  Function1.GITHUB_TOKEN=VAR1, GLOBAL_ENV_VAR=VAR2
          build_arguments: --parallel --debug
          context: CPE-OIDC
          filters: *filters
      - sam/deploy:
          name: deploy-job-test-container
          auth:
            - aws-cli/setup:
                role_arn: arn:aws:iam::122211685980:role/CPE_SAM_SEVERLESS_OIDC_TEST
                profile_name: OIDC-User
          profile_name: OIDC-User
          capabilities: CAPABILITY_IAM, CAPABILITY_NAMED_IAM
          template: "./sample_test/sam-container/template.yaml"
          stack_name: "orb-deploy-job-test-2"
          image_repositories: $DEMO_IMG_URI
          context: CPE-OIDC
          requires:
          - temp-cleanup
          validate: false
          filters: *filters
      - cleanup:
          context: CPE-OIDC
          requires:
          - deploy-job-test-container
          - deploy-job-test-app-same-line-arguments
      - orb-tools/pack:
          filters: *release-filters
      - orb-tools/publish:
          orb_name: circleci/aws-sam-serverless
          vcs_type: << pipeline.project.type >>
          pub_type: production
          enable_pr_comment: true
          requires:
            - orb-tools/pack
            - test_local_invoke
            - deploy-job-test-app
            - deploy-job-test-app-overrides-and-arguments
            - deploy-job-test-app-multiline-arguments
            - deploy-job-test-app-same-line-arguments
            - deploy-job-test-container
            - cleanup
          context: orb-publisher
          filters: *release-filters
