description: >
  Build your Lambda source.
  The sam build command iterates through the functions in your application, looks for a manifest file (such as requirements.txt) that contains the dependencies, and automatically creates deployment artifacts that you can deploy to Lambda using the sam package and sam deploy commands. You can also use sam build in combination with other commands like sam local invoke to test your application locally.

  Ensure CLI has been installed before utilizing.

parameters:
  validate:
    type: boolean
    default: true
    description: "Validate your template file. This will run unless manually set to false."
  build-dir:
    type: string
    description: The path to a folder where the built artifacts are stored.
    default: ""
  base-dir:
    type: string
    description: Resolves relative paths to the function's source code with respect to this folder. Use this if the AWS SAM template and your source code aren't in the same enclosing folder. By default, relative paths are resolved with respect to the template's location.
    default: ""
  template:
    type: string
    description: The AWS SAM template file
  profile-name:
    type: string
    description: Select a specific profile from your credential file to get AWS credentials.
    default: "default"
  use-container:
    type: boolean
    description: If your functions depend on packages that have natively compiled dependencies, use this flag to build your function inside an AWS Lambda-like Docker container.
    default: true
  aws-region:
    type: env_var_name
    description: Sets the AWS Region of the service (for example, us-east-1).
    default: "AWS_DEFAULT_REGION" # set this to aws install region
  debug:
    type: boolean
    description: Turns on debug logging.
    default: false

steps:
  - when:
      condition: << parameters.validate >>
      steps:
        - run:
            name: "Validating SAM template"
            command: |
              sam validate -t << parameters.template >> \
              --region $<< parameters.aws-region >> \
              --profile << parameters.profile-name >> \
              <<# parameters.debug >>--debug<</ parameters.debug >>

  - run:
      name: "Building SAM application"
      environment:
        SAM_PARAM_TEMPLATE: << parameters.template >>
        SAM_PARAM_BUILD_DIR: << parameters.build-dir >>
        SAM_PARAM_BASE_DIR: << parameters.base-dir >>
        SAM_PARAM_PROFILE: << parameters.profile-name >>
        SAM_PARAM_CONTAINER: << parameters.use-container >>
        SAM_PARAM_AWS_REGION: << parameters.aws-region >>
        SAM_PARAM_DEBUG: << parameters.debug >>
      command: <<include(scripts/build.sh)>>